### ISSUE TITLE
This error is prompted in blender3.5

### ISSUE THREAD

**Issue by chenpaner** [ymt3d/MPP-Blender-Addon#1] opened 2023-05-08 14:33 UTC
Python: Traceback (most recent call last):
  File "C:\Users\CP\AppData\Roaming\Blender Foundation\Blender\Big addons\addons\MPP-Blender-Addon-main\mpp_main.py", line 77, in modal
    bpy.types.SpaceView3D.draw_handler_remove(self._handle, 'WINDOW')
ValueError: callback_remove(handler): NULL handler given, invalid or already removed

**Comment by ymt3d** [comment] 2023-05-08 16:26
Thanks. I'll check it out.

**Comment by ymt3d** [comment] 2023-05-09 02:27
What version of the add-on are you using?

**Comment by chenpaner** [comment] 2023-05-09 02:40
> 您使用的是哪个版本的附加组件？

0.61 in blender3.5.1

**Comment by juliocargnin** [comment] 2023-05-15 05:26
Coming here to report the same issue on the same combination 0.61 in 3.5.1
It happen to me eventually whenever I paste the color and enter to Edit Mode immediately after the fact.
Sometimes it does fire the error, sometimes not... I couldn't make it completely reproducible.

**Comment by ymt3d** [comment] 2023-05-16 03:33
Thanks for the report. The hint that it happens when I go into edit mode is very helpful.
We will investigate.

**Comment by ymt3d** [comment] 2023-05-16 07:09
I have fixed the problem and would be happy to check.
v0.6.2
https://github.com/ymt3d/MPP-Blender-Addon/releases/tag/release

**Comment by juliocargnin** [comment] 2023-05-16 12:00
That error seems to be solved. Although, there is another error message flooding the terminal:

  File "/home/cosmomidias/.config/blender/3.5/scripts/addons/MPP-Blender-Addon-main/mpp_main.py", line 63, in draw_preview
    x, y = self.x + self.offset_x, self.y - self.offset_y - 50  # プレビュー画像の表示位置を設定
AttributeError: 'TextDisplay' object has no attribute 'offset_x'

This error seems not to affect the addon usability but it floods the terminal.
It spaws when you paste the color and hover the mouse pointer in and out the pasted object.

**Comment by juliocargnin** [comment] 2023-05-20 13:51
> File "/home/cosmomidias/.config/blender/3.5/scripts/addons/MPP-Blender-Addon-main/mpp_main.py", line 63, in draw_preview
> x, y = self.x + self.offset_x, self.y - self.offset_y - 50 # プレビュー画像の表示位置を設定
> AttributeError: 'TextDisplay' object has no attribute 'offset_x'

This error message seems to be fixed on version 0.6.8 :ok:

**Comment by chenpaner** [comment] 2023-05-21 12:19
Thank you very much for your repair. I have updated to 0.6.9. It runs perfectly. The version number written in your latest version of the file is not 0.6.9, but 0.6.0!

**Comment by ymt3d** [comment] 2023-05-21 12:53
Thanks for getting back to me! I realized that I had mistakenly published the old file as 0.6.9. Thanks for your help.

**Closed as completed** 2023-11-27 09:12 UTC
